### ISSUE TITLE
Code review for 1.4.0 Approved release

### ISSUE THREAD

**Issue by jholland-usgs** [usgs/asl-sensor-suite#31]
A code review is needed for https://github.com/usgs/asl-sensor-suite/tree/v1.4.0-rc1-reconciliation.
The review should follow this set of guidelines: 
https://github.com/usgs/best-practices/blob/master/software/reviews.md#code-review

**Comment by mguy-usgs** [comment]
Overall good package, I found no significant issues. Good javadoc in general. I successfully compiled, ran automated tests and ran and used the GUI. I only got it to use up to 230M of RAM, but it dropped back down to 42M (thanks java garbage collection!). The following are recommendations for consideration but not required.
 

Minor/Recommendations:
- Readme.md: this sentence is incomplete under Requirements, Software section "...produces an executable JAR file that can be launched either through command line or the . "
- I recommend adding a link or the DOI to the paper for this application into the Readme.md
-  https://github.com/usgs/asl-sensor-suite/blob/master/src/main/java/asl/sensor/CalProcessingServer.java#L54 * If a process is already using that port it silently terminates. - good to note this, but recommend logging an error to notify rather than "silently terminating"
- https://github.com/usgs/asl-sensor-suite/blob/d168357ee478122e0b1e33b25181bf503200f8ce/src/main/java/asl/sensor/CalProcessingServer.java#L104 recommend logging something rather than just exiting since an exception was caught
- https://github.com/usgs/asl-sensor-suite/blob/master/src/main/java/asl/sensor/CalProcessingServer.java#L121 also throws SeedFormatException and CodecException (same for rest of methods in this class that throw exceptions)
- https://github.com/usgs/asl-sensor-suite/blob/d168357ee478122e0b1e33b25181bf503200f8ce/src/main/java/asl/sensor/CalProcessingServer.java#L563 Several uses of SuppressWarnings, I recommend these are commented as why they are used and there (e.g. rather than changing/fixing the code)
- https://github.com/usgs/asl-sensor-suite/blob/d168357ee478122e0b1e33b25181bf503200f8ce/src/main/java/asl/sensor/CalProcessingServer.java#L619 if RandData is used externally then why is it defined as a nested class? Would defining it outside of this class (not nested) also fix your compiler warnings?
- recommend adding comments about units or formats for all the appropriate getters  in RandData (https://github.com/usgs/asl-sensor-suite/blob/d168357ee478122e0b1e33b25181bf503200f8ce/src/main/java/asl/sensor/CalProcessingServer.java#L621) 
- any time you have units good to add to comments, for example, is latestCorrelation is seconds? https://github.com/usgs/asl-sensor-suite/blob/d168357ee478122e0b1e33b25181bf503200f8ce/src/main/java/asl/sensor/experiment/AzimuthExperiment.java#L49
- the number 3 is hard coded several times in here, maybe make it a static variable for readability and ensured consistency especially with arrays - one example use is at https://github.com/usgs/asl-sensor-suite/blob/4e9f46bae3c5da5fdfde26083e11bf90a9962051/src/main/java/asl/sensor/experiment/NoiseExperiment.java#L41
-  you hard coded your array size here, just making sure you won't exceed it? https://github.com/usgs/asl-sensor-suite/blob/4e9f46bae3c5da5fdfde26083e11bf90a9962051/src/main/java/asl/sensor/experiment/ResponseExperiment.java#L52
- SineExperiment is missing the nice javadoc and intro comment like the rest of the classes https://github.com/usgs/asl-sensor-suite/blob/4e9f46bae3c5da5fdfde26083e11bf90a9962051/src/main/java/asl/sensor/experiment/SineExperiment.java#L10
- hard coded number 3 several times (line 30, 54, 89, 94) should this be a static to ensure consistency and help readability? https://github.com/usgs/asl-sensor-suite/blob/4e9f46bae3c5da5fdfde26083e11bf90a9962051/src/main/java/asl/sensor/experiment/SpectrumExperiment.java#L30
- commented out lines of code maybe removed? just looks like you changed your mind from using a Map to a List https://github.com/usgs/asl-sensor-suite/blob/4e9f46bae3c5da5fdfde26083e11bf90a9962051/src/main/java/asl/sensor/input/InstrumentResponse.java#L50
-  These tools seem fairly generic and maybe usable by others, may want to consider making them another project as a reusable library https://github.com/usgs/asl-sensor-suite/tree/v1.4.0-rc1-reconciliation/src/main/java/asl/sensor/utils
- I ran the automated tests (gradle test), but I did initially get an error on trying to clone seismic_test_data, so I cloned it myself into my local asL_sensor_suite/src/test/resources and then gradle test worked fine would be nice to just mention in the ReadMe.md that test data should go into this directory (in data dir) in asl_sensor_suite, but good to see the automated tests ( https://github.com/usgs/asl-sensor-suite/tree/v1.4.0-rc1-reconciliation/src/test/java/asl/sensor )
